version: '3.8'

services:
  hula-db:
    image: postgres:15
    container_name: hula_postgres
    restart: always
    environment:
      POSTGRES_DB: huladb
      POSTGRES_USER: huladbuser
      POSTGRES_PASSWORD: huladbpass
    ports:
      - "5436:5432"
    volumes:
      - hula_data:/var/lib/postgresql/data

  hula-api:
    build: .
    container_name: hula_backend
    ports:
      - "8585:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://hula-db:5432/huladb
      DATABASE_USERNAME: huladbuser
      DATABASE_PASSWORD: huladbpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - hula-db

volumes:
  hula_data:
